name: Generate README News every 12 hour

on: 
  schedule:
     - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
   stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Automated News Updation
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - run: npm i
      - run: node .   
        
            

      - name: Add to git repo
        run: |
           git add .
           git config --global user.name "GurjarKing"
           git config --global user.email "nitinnagar432@gmail.com"
           git commit -m "Automated News Update"
        
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
